- id: dryer_shed_rfid
  alias: Dryer Shed RFID
  trigger:
  - entity_id: binary_sensor.rpidryer_rfid
    from: 'off'
    platform: state
    to: 'on'
  action:
  - data:
      entity_id: lock.dryer_shed
    service: lock.unlock
- id: back_door_rfid
  alias: Back Door RFID
  trigger:
  - entity_id: binary_sensor.back_door_rfid
    from: 'off'
    platform: state
    to: 'on'
  action:
  - data:
      entity_id: input_boolean.backdoor_lock
    service: input_boolean.toggle
- action:
  - data:
      entity_id: light.beckys_office
    service: light.toggle
  alias: Flic - Becky Office - Single
  id: '1503804756412'
  trigger:
  - event_data:
      button_name: flic_80e4da721720
      click_type: single
    event_type: flic_click
    platform: event
- action:
  - data:
      entity_id: light.spare_room
    service: light.toggle
  alias: Flic - Spare Room - Single
  condition: []
  id: '1503824877416'
  trigger:
  - event_data:
      button_name: flic_80e4da720fb5
      click_type: single
    event_type: flic_click
    platform: event
