homeassistant:
  name: Home
  latitude: !secret homeassistant_latitude
  longitude: !secret homeassistant_longitude
  elevation: !secret homeassistant_elevation
  unit_system: metric
  time_zone: Pacific/Auckland
  packages: !include_dir_named packages
  customize: !include_dir_merge_named customize

automation: !include automations.yaml

binary_sensor: !include_dir_merge_list binary_sensor

config:

climate: !include_dir_merge_list climate

device_tracker: !include_dir_merge_list device_tracker

discovery:

frontend:

group: !include_dir_merge_named group

history:
  exclude:
    domains:
      - automation
      - weblink
      - updater
    entities:
      - sensor.last_boot
      - sensor.date

http:
  api_password: !secret http_password
  base_url: !secret http_url

input_boolean: !include_dir_merge_named input_boolean

input_select: !include_dir_merge_named input_select

light: !include_dir_merge_list light

lock: !include_dir_merge_list lock

logger:
  default: error
  logs:
    homeassistant.components.wemo: debug
    homeassistant.components.climate: info

media_player: !include_dir_merge_list media_player

mqtt:
  broker: 127.0.0.1
  port: 1883
  client_id: home-assistant
  username: !secret MQTT_username
  password: !secret MQTT_password

prometheus:

recorder:
  purge_days: 90
  db_url: !secret recorder_db
  exclude:
    domains:
      - automation
      - weblink
      - updater
    entities:
      - sun.sun
      - sensor.last_boot
      - sensor.date

remote: !include_dir_merge_list remote

sensor: !include_dir_merge_list sensor

switch: !include_dir_merge_list switch

sun:

updater:
  include_used_components: true

wemo:
