- alias: Lounge Motion
  trigger:
    - platform: state
      entity_id: binary_sensor.lounge_motion_inside_door
      to: 'on'
  condition: 
    - condition: state
      entity_id: input_boolean.ignore_lounge_motion
      state: 'off'
  action:
    - service: homeassistant.turn_on
      entity_id: script.lounge_timer_execute

- alias: Bathroom Motion
  trigger:
    - platform: state
      entity_id: binary_sensor.bathroom_motion
      to: 'on' 
  action:
    - service: homeassistant.turn_on
      entity_id: script.bathroom_timer_execute
