- alias: Lounge Off (Flic)
  trigger:
    - platform: state
      entity_id: binary_sensor.flic_lounge_click
      to: 'on'
  condition: 
    - condition: state
      entity_id: group.lounge_lights
      state: 'on'
  action:
    - service: homeassistant.turn_off
      entity_id: group.lounge_lights
    - service: homeassistant.turn_off
      entity_id: binary_sensor.flic_lounge_click


- alias: Lounge On (Flic)
  trigger:
    - platform: state
      entity_id: binary_sensor.flic_lounge_click
      to: 'on'
  condition: 
    - condition: state
      entity_id: group.lounge_lights
      state: 'off'
  action:
    - service: homeassistant.turn_on
      entity_id: group.lounge_lights
    - service: homeassistant.turn_off
      entity_id: binary_sensor.flic_lounge_click

